name: checks
on:
  push:
  schedule:
    - cron: "0 13 * * 1"
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run validate
      - run: npm run check:cmr
      - run: npm run check:links
        continue-on-error: true
